export const PLANS = [
  {
    key: 'starter',
    name: 'Starter',
    monthlyUsd: 29,
    annualUsd: 290,
    monthlyAed: 107,
    annualAed: 1070,
    description: 'For small teams getting started.',
    features: [
      'Up to 10 team members',
      'Up to 100 tools',
      'Tool assignment & history',
      'Basic reports',
      'Email support',
    ],
    highlight: false,
    ctaLabel: 'Start free trial',
  },
  {
    key: 'pro',
    name: 'Pro',
    monthlyUsd: 79,
    annualUsd: 790,
    monthlyAed: 290,
    annualAed: 2900,
    description: 'For growing teams that need more.',
    features: [
      'Unlimited team members',
      'Unlimited tools',
      'Everything in Starter',
      'Compliance & calibration tracking',
      'PDF & Excel exports',
      'Approval workflows',
      'Priority support',
    ],
    highlight: true,
    ctaLabel: 'Start free trial',
  },
]
