name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --no-sound-null-safety || true

      - name: Build APK (Debug)
        run: flutter build apk --debug --no-sound-null-safety

      - name: Build APK (Release)
        run: flutter build apk --release --no-sound-null-safety

      - name: Build App Bundle (Release)
        run: flutter build appbundle --release --no-sound-null-safety

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: RGS-Tools-Android-Debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: RGS-Tools-Android-Release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: RGS-Tools-Android-Bundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 90

      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

