name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Xcode version
      run: xcodebuild -version
      
    - name: Clean everything
      run: |
        flutter clean
        rm -rf ios/build/
        rm -rf build/
        rm -rf ios/Pods/
        rm -rf ios/Podfile.lock
        
    - name: Flutter pub get
      run: flutter pub get
      
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install
        
    - name: Check iOS configuration
      run: |
        flutter config --list
        flutter devices
        
    - name: Build iOS app
      run: |
        flutter build ios --release --no-codesign
        echo "iOS build completed"
        
    - name: List build artifacts
      run: |
        find build/ios -name "*.app" -o -name "*.ipa" || echo "No build artifacts found"
        
    - name: Create IPA manually
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../rgs-tools.ipa Payload/
        echo "IPA created successfully"
        
    - name: List final artifacts
      run: |
        ls -la *.ipa || echo "No IPA files found"
        find . -name "*.ipa" || echo "No IPA files found"
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: rgs-tools-ios
        path: rgs-tools.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-build-logs
        path: |
          build/
          ios/
        retention-days: 7