name: Build iOS 18 IPA for AltStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
        
    - name: Xcode version
      run: xcodebuild -version
      
    - name: Clean everything
      run: |
        flutter clean
        rm -rf ios/build/
        rm -rf build/
        rm -rf ios/Pods/
        rm -rf ios/Podfile.lock
        
    - name: Flutter pub get
      run: flutter pub get
      
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --verbose
        
    - name: Check iOS configuration
      run: |
        flutter config --list
        flutter devices
        
    - name: Check iOS project configuration
      run: |
        echo "Checking iOS project configuration..."
        cat ios/Podfile
        echo "---"
        grep -r "IPHONEOS_DEPLOYMENT_TARGET" ios/Runner.xcodeproj/project.pbxproj
        echo "---"
        ls -la ios/
        
    - name: Build iOS 18 app for AltStore
      run: |
        flutter build ios --release --no-codesign --target-platform ios-arm64
        echo "iOS 18 build completed for AltStore sideloading"
        
    - name: List build artifacts
      run: |
        find build/ios -name "*.app" -o -name "*.ipa" || echo "No build artifacts found"
        
    - name: Create IPA for AltStore
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../rgs-tools-altstore.ipa Payload/
        echo "IPA created successfully for AltStore sideloading"
        
    - name: List final artifacts
      run: |
        ls -la *.ipa || echo "No IPA files found"
        find . -name "*.ipa" || echo "No IPA files found"
        
    - name: Upload IPA artifact for AltStore
      uses: actions/upload-artifact@v4
      with:
        name: rgs-tools-altstore-ipa
        path: rgs-tools-altstore.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-build-logs
        path: |
          build/
          ios/
        retention-days: 7