name: Build iOS IPA for iOS 18+

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: Xcode version
      run: xcodebuild -version
      
    - name: Clean iOS build directory
      run: |
        rm -rf ios/build/
        rm -rf build/ios/
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod deintegrate || true
        pod install --repo-update
        
    - name: Flutter clean
      run: flutter clean
      
    - name: Flutter pub get
      run: flutter pub get
      
    - name: Check iOS configuration
      run: |
        flutter config --list
        flutter devices
      
    - name: Build iOS app (debug first)
      run: |
        flutter build ios --debug --no-codesign
        echo "Debug build completed"
        
    - name: List debug build artifacts
      run: |
        find build/ios -name "*.app" -o -name "*.ipa" | head -10
        
    - name: Build iOS IPA for iOS 18+
      run: |
        flutter build ipa --release --no-codesign
        echo "iOS 18+ IPA build completed"
        
    - name: List build artifacts
      run: |
        ls -la build/ios/ipa/ || echo "No IPA directory found"
        find build/ios -name "*.ipa" || echo "No IPA files found"
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: rgs-tools-ios-18
        path: build/ios/ipa/*.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-build-logs
        path: |
          build/
          ios/
        retention-days: 7