name: Build iOS IPA for AltStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Clean and build
      run: |
        flutter clean
        flutter pub get
        cd ios && pod install
        flutter build ios --release --no-codesign
        
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../rgs-tools.ipa Payload/
        echo "IPA created successfully"
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: rgs-tools-ipa
        path: rgs-tools.ipa
        retention-days: 30