name: Build iOS IPA for AltStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Xcode version
      run: xcodebuild -version
      
    - name: Clean project
      run: |
        flutter clean
        rm -rf ios/build/
        rm -rf build/
        rm -rf ios/Pods/
        rm -rf ios/Podfile.lock
        
    - name: Flutter pub get
      run: flutter pub get
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --verbose
      
    - name: Build iOS app
      run: flutter build ios --release --no-codesign --verbose
        
    - name: List build artifacts
      run: |
        find build/ios -name "*.app" -o -name "*.ipa" || echo "No build artifacts found"
        ls -la build/ios/iphoneos/ || echo "No iphoneos directory found"
        
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../rgs-tools.ipa Payload/
        echo "IPA created successfully"
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: rgs-tools-ipa
        path: rgs-tools.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-build-logs
        path: |
          build/
          ios/
        retention-days: 7